title: "RalfSei"
description: "Persönliche Website & Projekte"
url: "https://ralfsei.github.io"
baseurl: ""

lang: "de"
timezone: "Europe/Berlin"
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: "/:name/"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      nav: true
      nav_order: 100
      show_on_home: true