title: "RalfSei"
markdown: kramdown

collections:
  pages:
    output: true
    permalink: "/:name/"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      nav: true
      nav_order: 100
      show_on_home: true

#title: KI-Projekte von Ralf Seidenschwang
#theme: jekyll-theme-cayman
#markdown: kramdown
exclude:
  - legaltech-codebeispiel   # ❌ blockiert deine Unterseite