title: "RalfSei"
markdown: kramdown

collections:
  pages:
    output: true
    permalink: "/:name/"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      nav: true
      nav_order: 100
      show_on_home: true

# Optionales Theme (kannst du aktivieren, wenn du möchtest)
# theme: jekyll-theme-cayman

# Diese Dateien oder Ordner werden beim Bauen der Website ausgeschlossen
exclude:
  - node_modules
  - README.md
  - legaltech-codebeispiel
